### ISSUE TITLE
org.freedesktop.Avahi.NotSupportedError error

### ISSUE THREAD

**Issue by drmikecrowe** [hardillb/nginx-proxy-avahi-helper#7]
Any thoughts on this error?

```log
forego      | starting cname.1 on port 17100
cname.1     | Traceback (most recent call last):
cname.1     |   File "/usr/src/app/cname.py", line 93, in <module>
cname.1     |     main()
cname.1     |   File "/usr/src/app/cname.py", line 81, in main
cname.1     |     status = publisher.publish_cname(cname, True)
cname.1     |   File "/usr/local/lib/python3.9/site-packages/mpublisher/mpublisher.py", line 117, in publish_cname
cname.1     |     group.AddRecord(avahi.IF_UNSPEC, avahi.PROTO_UNSPEC, dbus.UInt32(0), cname.encode("ascii"),
cname.1     |   File "/usr/local/lib/python3.9/site-packages/dbus/proxies.py", line 72, in __call__
cname.1     |     return self._proxy_method(*args, **keywords)
cname.1     |   File "/usr/local/lib/python3.9/site-packages/dbus/proxies.py", line 141, in __call__
cname.1     |     return self._connection.call_blocking(self._named_service,
cname.1     |   File "/usr/local/lib/python3.9/site-packages/dbus/connection.py", line 634, in call_blocking
cname.1     |     reply_message = self.send_message_with_reply_and_block(
cname.1     | dbus.exceptions.DBusException: org.freedesktop.Avahi.NotSupportedError: Not supported
```

**Comment by hardillb** [comment]
Nope, first guess would be to check what name you were trying to use, but other than that it will be digging in the avahi dbus doc/src

**Comment by beorn** [comment]
Maybe you're trying to use it on a macOS host?
https://stackoverflow.com/questions/44078097/how-do-i-advertise-and-browse-mdns-from-within-docker-container
